### PR TITLE
Extract tymodel to json

### PR DESCRIPTION
**Pull request by doehyunbaek**
Currently has two problems.

1. TyModel is not version dendent.

Currently, TyModel is [hardcode](https://github.com/es-meta/esmeta/blob/57fe735a1fca52bbfca018d171f493335f2a4dea/src/main/scala/esmeta/ty/TyModel.scala#L208) into TyModel.scala and is being used globally.

Usages of global TyModel is as follows:
- [Parsing NameTy](https://github.com/es-meta/esmeta/blob/a0c9b7cfa17e71da9186e73417b5b3c8d490e2ad/src/main/scala/esmeta/lang/util/Parser.scala#L1167)
- [Various functions related to NameTy](https://github.com/es-meta/esmeta/blob/4b66aa98546fa24b1a3c5ad04fe6cd08f22824e7/src/main/scala/esmeta/ty/NameTy.scala#L11)
- [Containment check for MapObj](https://github.com/es-meta/esmeta/blob/9acc5430167456f2c98f473c720340974dfcb5a4/src/main/scala/esmeta/ty/ValueTy.scala#L128)

2. Hack in NameTy

This is also related to [hack in NameTy](https://github.com/es-meta/esmeta/commit/9a4745ce3d5cadeed1ef8f9232a206e44e2ed7b1#diff-c174a7a19b38abb716b8b61c76da62733d824f1f1b245f5ac1af5d0a61685717R13-R17), as there are circular dependencies between NameTy functions and TyModel, before you just hardcoded TyModel and as it was provided from the start it did not cause problem. Now, as TyModel itself should also be parsed out of json and NameTy functions are invoked when parsing, it causes problem.

It seems that to resolve above two problems, you should make above three usage sites not to use global TyModel but version-dependent TyModel as parameter, currently working on this solution.

### CODE REVIEW

**Comment by doehyunbaek** [comment]
I tried to solve the first problem with https://github.com/es-meta/esmeta/pull/180/commits/7ccad177a77bb5e2ef23f254068886b4dff07a36

**Comment by doehyunbaek** [comment]
Currently checking e2e test failing.

**Comment by doehyunbaek** [comment]
[a8d0643](https://github.com/es-meta/esmeta/pull/180/commits/a8d0643d122031113e98e696438a03e899be0315) fixes the e2e test.

**Comment by jhnaldo** [comment]
I merged this PR after refactoring the code. Thanks! Because of the dependency issue, I dropped the feature for version-dependent support of the type model. This PR only supports the JSON-based management of the type model.

**Pull request merged**
