### PR TITLE
Modified `ETypeCheck` with `Ty`

### PR DESCRIPTION
**Pull request by duncan020313**
If ETypeCheck is about productions, I replaced EStr with EGrammar for each production.

### CODE REVIEW

**Comment by jhnaldo** [comment]
It is related to #89.

**Comment by jhnaldo** [comment]
Can you list the changed results and explain why the current results are better than before?

**Comment by duncan020313** [comment]
> Can you list the changed results and explain why the current results are better than before?

I searched with the "grammar" string and got the following result.

./LabelledItem[0,0].TopLevelVarDeclaredNames.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./CaseBlock[1,1].CaseBlockEvaluation.ir:    let A = (get-children (grammar |CaseClause|[]) this[0])
./CaseBlock[1,1].CaseBlockEvaluation.ir:    let B = (get-children (grammar |CaseClause|[]) this[2])
./IsLabelledFunction.ir:  if (! (? stmt: (grammar |LabelledStatement|[FFF]))) {
./IsLabelledFunction.ir:  if (? item: (grammar |LabelledItem1|[FFF])) {
./MethodDefinition[4,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./ArrowParameters[1,0].ExpectedArgumentCount.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./AssignmentElement[0,1].KeyedDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentElement[0,1].KeyedDestructuringAssignmentEvaluation.ir:  if (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF]))) {
./AssignmentElement[0,1].KeyedDestructuringAssignmentEvaluation.ir:    let assignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./ParseScript.ir:  let script = (parse sourceText (grammar |Script|[]))
./GeneratorMethod[0,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./GeneratorMethod[0,0].HasDirectSuper.ir:  sdo-call %1 = this[2]->Contains((grammar |SuperCall|[]))
./PerformEval.ir:  let script = (parse %3 (grammar |Script|[]))
./PerformEval.ir:  sdo-call %4 = script->Contains((grammar |ScriptBody|[]))
./PerformEval.ir:    sdo-call %6 = body->Contains((grammar |NewTarget|[]))
./PerformEval.ir:    sdo-call %8 = body->Contains((grammar |SuperProperty|[]))
./PerformEval.ir:    sdo-call %10 = body->Contains((grammar |SuperCall|[]))
./AsyncGeneratorMethod[0,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./AsyncGeneratorMethod[0,0].HasDirectSuper.ir:  sdo-call %1 = this[2]->Contains((grammar |SuperCall|[]))
./BlockDeclarationInstantiation.ir:    if (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF]))) {
./StatementListItem[0,0].LexicallyDeclaredNames.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./StatementListItem[0,0].LexicallyScopedDeclarations.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./ParseModule.ir:  let body = (parse sourceText (grammar |Module|[]))
./SourceTextModuleRecord.InitializeEnvironment.ir:      if (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF]))) {
./StatementListItem[1,0].TopLevelLexicallyDeclaredNames.ir:  if (? this[0]: (grammar |Declaration0|[FF])) {
./PrimaryExpression[12,0].IsFunctionDefinition.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./GlobalDeclarationInstantiation.ir:    if (! (|| (|| (? d: (grammar |VariableDeclaration|[FFF])) (? d: (grammar |ForBinding|[FF]))) (? d: (grammar |BindingIdentifier|[FF])))) {
./GlobalDeclarationInstantiation.ir:      assert (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF])))
./GlobalDeclarationInstantiation.ir:    if (|| (|| (? d: (grammar |VariableDeclaration|[FFF])) (? d: (grammar |ForBinding|[FF]))) (? d: (grammar |BindingIdentifier|[FF]))) {
./MemberExpression[0,0].IsDestructuring.ir:  if (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF]))) {
./MethodDefinition[0,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./MethodDefinition[0,0].HasDirectSuper.ir:  sdo-call %1 = this[2]->Contains((grammar |SuperCall|[]))
./StatementListItem[1,0].TopLevelVarScopedDeclarations.ir:  if (? this[0]: (grammar |Declaration0|[FF])) {
./MethodDefinition[5,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./MethodDefinition[5,0].HasDirectSuper.ir:  sdo-call %1 = this[2]->Contains((grammar |SuperCall|[]))
./EvalDeclarationInstantiation.ir:    if (! (|| (|| (? d: (grammar |VariableDeclaration|[FFF])) (? d: (grammar |ForBinding|[FF]))) (? d: (grammar |BindingIdentifier|[FF])))) {
./EvalDeclarationInstantiation.ir:      assert (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF])))
./EvalDeclarationInstantiation.ir:    if (|| (|| (? d: (grammar |VariableDeclaration|[FFF])) (? d: (grammar |ForBinding|[FF]))) (? d: (grammar |BindingIdentifier|[FF]))) {
./AssignmentElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:  if (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF]))) {
./AssignmentElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:    let nestedAssignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./CreateDynamicFunction.ir:    let exprSym = (grammar |FunctionExpression|[])
./CreateDynamicFunction.ir:    let bodySym = (grammar |FunctionBody|[FF])
./CreateDynamicFunction.ir:    let parameterSym = (grammar |FormalParameters|[FF])
./CreateDynamicFunction.ir:      let exprSym = (grammar |GeneratorExpression|[])
./CreateDynamicFunction.ir:      let bodySym = (grammar |GeneratorBody|[])
./CreateDynamicFunction.ir:      let parameterSym = (grammar |FormalParameters|[TF])
./CreateDynamicFunction.ir:        let exprSym = (grammar |AsyncFunctionExpression|[])
./CreateDynamicFunction.ir:        let bodySym = (grammar |AsyncFunctionBody|[])
./CreateDynamicFunction.ir:        let parameterSym = (grammar |FormalParameters|[FT])
./CreateDynamicFunction.ir:        let exprSym = (grammar |AsyncGeneratorExpression|[])
./CreateDynamicFunction.ir:        let bodySym = (grammar |AsyncGeneratorBody|[])
./CreateDynamicFunction.ir:        let parameterSym = (grammar |FormalParameters|[TT])
./PrimaryExpression[12,0].AssignmentTargetType.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./CoverCallExpressionAndAsyncArrowHead[0,0].IsSimpleParameterList.ir:  let head = (parse this (grammar |AsyncArrowHead|[]))
./AssignmentElement[0,0].KeyedDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentElement[0,0].KeyedDestructuringAssignmentEvaluation.ir:  if (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF]))) {
./AssignmentElement[0,0].KeyedDestructuringAssignmentEvaluation.ir:    let assignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./PrimaryExpression[12,0].NamedEvaluation.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./HexNonSurrogate[0,0].CharacterValue.ir:  sdo-call %0 = (grammar |HexDigits|[])->MV()
./StatementListItem[1,0].TopLevelLexicallyScopedDeclarations.ir:  if (? this[0]: (grammar |Declaration0|[FF])) {
./AsyncMethod[0,0].HasDirectSuper.ir:  sdo-call %0 = this[1]->Contains((grammar |SuperCall|[]))
./AsyncMethod[0,0].HasDirectSuper.ir:  sdo-call %1 = this[2]->Contains((grammar |SuperCall|[]))
./ForInOfBodyEvaluation.ir:    assert (? lhs: (grammar |LeftHandSideExpression|[FF]))
./ForInOfBodyEvaluation.ir:    let assignmentPattern = (parse lhs (grammar |AssignmentPattern|[]))
./ForInOfBodyEvaluation.ir:      assert (? lhs: (grammar |ForDeclaration|[FF]))
./ForInOfBodyEvaluation.ir:          assert (? lhs: (grammar |ForBinding|[FF]))
./ForInOfBodyEvaluation.ir:          assert (? lhs: (grammar |ForDeclaration|[FF]))
./ArrowParameters[1,0].IteratorBindingInitialization.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./FunctionDeclarationInstantiation.ir:    if (! (|| (|| (? d: (grammar |VariableDeclaration|[FFF])) (? d: (grammar |ForBinding|[FF]))) (? d: (grammar |BindingIdentifier|[FF])))) {
./FunctionDeclarationInstantiation.ir:      assert (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF])))
./AssignmentElement[0,1].IteratorDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentElement[0,1].IteratorDestructuringAssignmentEvaluation.ir:  if (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF]))) {
./AssignmentElement[0,1].IteratorDestructuringAssignmentEvaluation.ir:    let nestedAssignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./CaseBlock[1,2].CaseBlockEvaluation.ir:    let A = (get-children (grammar |CaseClause|[]) this[0])
./CaseBlock[1,2].CaseBlockEvaluation.ir:    let B = (get-children (grammar |CaseClause|[]) this[2])
./INTRINSICS.parseFloat.ir:  let parsedNumber = (parse %2 (grammar |StrDecimalLiteral|[]))
./INTRINSICS.JSON.parse.ir:  let script = (parse %1 (grammar |Script|[]))
./StatementListItem[0,0].TopLevelVarDeclaredNames.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./AssignmentExpression[4,0].Evaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentExpression[4,0].Evaluation.ir:  let assignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./AsyncArrowFunction[1,0].Contains.ir:  if (! (|| (|| (|| (|| (= symbol (grammar |NewTarget|[])) (= symbol (grammar |SuperProperty|[]))) (= symbol (grammar |SuperCall|[]))) (= symbol "super")) (= symbol "this"))) {
./AsyncArrowFunction[1,0].Contains.ir:  let head = (parse this[0] (grammar |AsyncArrowHead|[]))
./LabelledItem[0,0].TopLevelVarScopedDeclarations.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./ArrowParameters[1,0].IsSimpleParameterList.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./CaseBlock[1,0].CaseBlockEvaluation.ir:    let A = (get-children (grammar |CaseClause|[]) this[0])
./CaseBlock[1,0].CaseBlockEvaluation.ir:    let B = (get-children (grammar |CaseClause|[]) this[2])
./HexLeadSurrogate[0,0].CharacterValue.ir:  sdo-call %0 = (grammar |HexDigits|[])->MV()
./AsyncArrowFunction[0,0].Contains.ir:  if (! (|| (|| (|| (|| (= symbol (grammar |NewTarget|[])) (= symbol (grammar |SuperProperty|[]))) (= symbol (grammar |SuperCall|[]))) (= symbol "super")) (= symbol "this"))) {
./AssignmentRestElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentRestElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:  if (! (|| (? this[0]: (grammar |ObjectLiteral|[FF])) (? this[0]: (grammar |ArrayLiteral|[FF])))) {
./AssignmentRestElement[0,0].IteratorDestructuringAssignmentEvaluation.ir:  let nestedAssignmentPattern = (parse this[0] (grammar |AssignmentPattern|[]))
./PrimaryExpression[12,0].HasCallInTailPosition.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./CaseBlock[1,3].CaseBlockEvaluation.ir:    let A = (get-children (grammar |CaseClause|[]) this[0])
./CaseBlock[1,3].CaseBlockEvaluation.ir:    let B = (get-children (grammar |CaseClause|[]) this[2])
./StatementListItem[1,0].TopLevelVarDeclaredNames.ir:  if (? this[0]: (grammar |Declaration0|[FF])) {
./AsyncArrowFunction[1,0].InstantiateAsyncArrowFunctionExpression.ir:  let head = (parse this[0] (grammar |AsyncArrowHead|[]))
./ArrowParameters[1,0].BoundNames.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./CallExpression[0,0].Evaluation.ir:  let expr = (parse this[0] (grammar |CallMemberExpression|[]))
./ArrowParameters[1,0].Contains.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./PrimaryExpression[12,0].Evaluation.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./StatementListItem[0,0].TopLevelVarScopedDeclarations.ir:  if (? this[0]: (grammar |Statement10|[FFF])) {
./HexTrailSurrogate[0,0].CharacterValue.ir:  sdo-call %0 = (grammar |HexDigits|[])->MV()
./CaseBlock[0,1].CaseBlockEvaluation.ir:  let A = (get-children (grammar |CaseClause|[]) this[0])
./ArrowParameters[1,0].ContainsExpression.ir:  let formals = (parse this[0] (grammar |ArrowFormalParameters|[]))
./PrimaryExpression[12,0].HasName.ir:  let expr = (parse this[0] (grammar |ParenthesizedExpression|[]))
./ArrowFunction[0,0].Contains.ir:  if (! (|| (|| (|| (|| (= symbol (grammar |NewTarget|[])) (= symbol (grammar |SuperProperty|[]))) (= symbol (grammar |SuperCall|[]))) (= symbol "super")) (= symbol "this"))) {
./CoverCallExpressionAndAsyncArrowHead[0,0].BoundNames.ir:  let head = (parse this (grammar |AsyncArrowHead|[]))

This is a CondStep for BlockDeclarationInstantiation Algorithm. Originally, It changed as follows.
if (|| (|| (|| (? d: "FunctionDeclaration")) (? d: "GeneratorDeclaration")) (? d: "AsyncFunctionDeclaration")) (? d: "AsyncGeneratorDeclaration"))
Currently, it changed as follows.
if (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF])))

I think the current version is better because we can use information that each type is grammar production such as the number of parameters. So we can detect spec errors more precisely. But the current interpreter and transition just use the information of Lhs name. So I think we need to fix this.

**Comment by jhnaldo** [comment]
I think you listed all the `EGrammar` in the compiled IR program of ES2022. However, I asked about all the IR instructions "affected by" your PR.

> This is a CondStep for BlockDeclarationInstantiation Algorithm. Originally, It changed as follows.
> ```
> if (|| (|| (|| (? d: "FunctionDeclaration")) (? d: "GeneratorDeclaration")) (? d: "AsyncFunctionDeclaration")) (? d: "AsyncGeneratorDeclaration"))
> ```
> Currently, it changed as follows.
> ```
> if (|| (|| (|| (? d: (grammar |FunctionDeclaration|[FFF])) (? d: (grammar |GeneratorDeclaration|[FFF]))) (? d: (grammar |AsyncFunctionDeclaration|[FFF]))) (? d: (grammar |AsyncGeneratorDeclaration|[FFF])))
> ```

Is it a correct compilation? For example, the following original IR `Expr` checked whether _d_ is a parsing result with `FunctionDeclaration` 
```
(? d: "FunctionDeclaration")
```
However, the following IR `Expr` changed by this PR checked whether _d_ is a parsing result with `FunctionDeclaration` and boolean parameters `FFF`.
```
(? d: (grammar |FunctionDeclaration|[FFF])
```
Let us discuss it offline.

**Pull request closed without merging**
